apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitmproxy
  namespace: mitmproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mitmproxy
  template:
    metadata:
      labels:
        app: mitmproxy
    spec:
      containers:
      - name: mitmproxy
        image: mitmproxy/mitmproxy:latest
        command: ["/bin/sh", "-c", "mitmweb --web-host 0.0.0.0 --web-port 8081 --listen-port 8080 --no-web-open-browser --set web_password=''"]
        ports:
        - name: proxy
          containerPort: 8080
        - name: web
          containerPort: 8081
